name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & Push Image
        run: |
          echo ${{ secrets.DOCKERTOKEN }} | docker login -u "yorenshgupta9" --password-stdin
          docker build -t <yorenshgupta9>/fastapi-app:latest .
          docker push <yorenshgupta9>/fastapi-app:latest
