name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: "yorenshgupta9"
          DOCKER_PASSWORD: ${{ secrets.DOCKERTOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t yorenshgupta9/fastapi-app:latest .
          docker push yorenshgupta9/fastapi-app:latest
